import{a as L,S as v,i}from"./assets/vendor-DqB7j7Ix.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function a(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=a(o);fetch(o.href,r)}})();const S="https://pixabay.com/api/",w="51298841-cc5bd03add2d04ff440a90847";function p(e,t=1){const a={key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return L.get(S,{params:a}).then(n=>n.data)}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function h(e){const t=e.map(({webformatURL:a,largeImageURL:n,tags:o,likes:r,views:c,comments:y,downloads:b})=>`
                <li class="gallery-item">
                    <a href="${n}" class="gallery-link">
                        <img src="${a}" alt="${o}" class="gallery-image"/>
                        <div class="info">
                            <p><span>Likes</span> ${r}</p>
                            <p><span>Views</span> ${c}</p>
                            <p><span>Comments</span> ${y}</p>
                            <p><span>Downloads</span> ${b}</p>
                        </div>
                    </a>
                </li>`).join("");f.insertAdjacentHTML("beforeend",t),q.refresh()}function E(){f.innerHTML=""}function T(){m.classList.add("is-visible")}function u(){m.classList.remove("is-visible")}function R(){const e=document.querySelector(".load-more-container");e&&e.classList.remove("is-hidden")}function d(){const e=document.querySelector(".load-more-container");e&&e.classList.add("is-hidden")}function B(){const e=document.querySelector(".back-to-top-btn");e&&e.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})})}const g=document.querySelector(".form"),O=g.querySelector('input[name="search-text"]');let l="",s=1;g.addEventListener("submit",function(e){if(e.preventDefault(),l=O.value.trim(),s=1,!l){i.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}T(),E(),d(),setTimeout(async()=>{try{const t=await p(l,s);if(u(),t.hits.length===0){i.error({title:"Oops",message:"Sorry, no images found!",position:"topRight"});return}h(t.hits),t.totalHits>15&&(R(),B()),s*15>=t.totalHits&&(d(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{u(),i.error({title:"Error",message:"Something went wrong.",position:"topRight"})}},1200)});document.addEventListener("click",async function(e){if(e.target.id==="load-more-btn"){s+=1;try{const t=await p(l,s);u(),h(t.hits),P(),s*15>=t.totalHits&&(d(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{u(),i.error({title:"Error",message:"Could not load more images.",position:"topRight"})}}});function P(){const e=document.querySelector(".gallery-item");if(e){const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
