import{a as w,S,i as n}from"./assets/vendor-DqB7j7Ix.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const q="https://pixabay.com/api/",T="51298841-cc5bd03add2d04ff440a90847";async function p(t,e=1){const s={key:T,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e};return(await w.get(q,{params:s})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),E=new S(".gallery a",{captionsData:"alt",captionDelay:250});function h(t){const e=t.map(({webformatURL:s,largeImageURL:a,tags:o,likes:r,views:c,comments:L,downloads:v})=>`
                <li class="gallery-item">
                    <a href="${a}" class="gallery-link">
                        <img src="${s}" alt="${o}" class="gallery-image"/>
                        <div class="info">
                            <p><span>Likes</span> ${r}</p>
                            <p><span>Views</span> ${c}</p>
                            <p><span>Comments</span> ${L}</p>
                            <p><span>Downloads</span> ${v}</p>
                        </div>
                    </a>
                </li>`).join("");f.insertAdjacentHTML("beforeend",e),E.refresh()}function R(){f.innerHTML=""}function g(){m.classList.add("is-visible")}function u(){m.classList.remove("is-visible")}function y(){const t=document.querySelector(".load-more-container");t&&t.classList.remove("is-hidden")}function d(){const t=document.querySelector(".load-more-container");t&&t.classList.add("is-hidden")}function B(){document.querySelector(".back-to-top-btn").addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})})}const b=document.querySelector(".form"),O=b.querySelector('input[name="search-text"]');let l="",i=1;b.addEventListener("submit",async function(t){if(t.preventDefault(),l=O.value.trim(),i=1,!l){n.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}g(),R(),d();try{const e=await p(l,i);if(u(),e.hits.length===0){n.error({title:"Oops",message:"Sorry, no images found!",position:"topRight"});return}h(e.hits),e.totalHits>15&&(y(),B()),i*15>=e.totalHits&&(d(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{u(),n.error({title:"Error",message:"Something went wrong.",position:"topRight"})}});document.addEventListener("click",async function(t){if(t.target.id==="load-more-btn"){i+=1,d(),g();try{const e=await p(l,i);u(),h(e.hits),P(),i*15>=e.totalHits?(d(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):y()}catch{u(),n.error({title:"Error",message:"Could not load more images.",position:"topRight"})}}});function P(){const t=document.querySelector(".gallery-item");if(t){const{height:e}=t.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
