import{a as q,S as B,i as c}from"./assets/vendor-DqB7j7Ix.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(o){if(o.ep)return;o.ep=!0;const r=n(o);fetch(o.href,r)}})();const H="https://pixabay.com/api/",O="51298841-cc5bd03add2d04ff440a90847";async function y(t,e=1){const n={key:O,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e};return(await q.get(H,{params:n})).data}const g=document.querySelector(".gallery"),w=document.querySelector(".loader"),m=document.querySelector(".back-to-top-btn"),P=new B(".gallery a",{captionsData:"alt",captionDelay:250});function b(t){const e=t.map(({webformatURL:n,largeImageURL:i,tags:o,likes:r,views:a,comments:E,downloads:T})=>`
                <li class="gallery-item">
                    <a href="${i}" class="gallery-link">
                        <img src="${n}" alt="${o}" class="gallery-image"/>
                        <div class="info">
                            <p><span>Likes</span> ${r}</p>
                            <p><span>Views</span> ${a}</p>
                            <p><span>Comments</span> ${E}</p>
                            <p><span>Downloads</span> ${T}</p>
                        </div>
                    </a>
                </li>`).join("");g.insertAdjacentHTML("beforeend",e),P.refresh()}function R(){g.innerHTML=""}function L(){w.classList.add("is-visible")}function d(){w.classList.remove("is-visible")}function S(){const t=document.querySelector(".load-more-container");t&&t.classList.remove("is-hidden")}function u(){const t=document.querySelector(".load-more-container");t&&t.classList.add("is-hidden")}function $(){m.style.display="block",m.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})})}function f(){m.style.display="none"}const v=document.querySelector(".form"),k=v.querySelector('input[name="search-text"]'),C=document.getElementById("load-more-btn");let l="",s=1,h=!1,p=!1;v.addEventListener("submit",async function(t){if(t.preventDefault(),l=k.value.trim(),s=1,!l){c.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}f(),L(),R(),u();try{const e=await y(l,s);if(d(),e.hits.length===0){c.error({title:"Oops",message:"Sorry, no images found!",position:"topRight"});return}b(e.hits),$(),e.totalHits>15&&S(),s*15>=e.totalHits&&(u(),h=!0,p=!1,f())}catch{d(),f(),c.error({title:"Error",message:"Something went wrong.",position:"topRight"})}});C.addEventListener("click",async function(t){s+=1,u(),L();try{const e=await y(l,s);d(),b(e.hits),M(),s*15>=e.totalHits?(u(),h=!0,p=!1):S()}catch{d(),c.error({title:"Error",message:"Could not load more images.",position:"topRight"})}});function M(){const t=document.querySelector(".gallery-item");if(t){const{height:e}=t.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}window.addEventListener("scroll",()=>{const t=window.scrollY,e=window.innerHeight,n=document.body.scrollHeight;h&&!p&&t+e>=n&&(c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),p=!0)});
//# sourceMappingURL=index.js.map
